# Generated by Django 4.1.2 on 2022-11-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(default='0 0 * * *', max_length=50)),
                ('pre_hook', models.CharField(blank=True, max_length=1024)),
                ('post_hook', models.CharField(blank=True, max_length=1024)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cluster.dockerservice')),
            ],
        ),
        migrations.CreateModel(
            name='ResticBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('protocol', models.CharField(choices=[('SFTP', 'Secure File Transfer Protocol (SFTP)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SFTPAttributeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024)),
                ('hostname', models.CharField(max_length=1024)),
                ('port', models.PositiveIntegerField(default=22)),
                ('backend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_attrs', to='restic.resticbackend')),
            ],
        ),
        migrations.CreateModel(
            name='ResticRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1024)),
                ('backupconfig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restic.backupconfig')),
                ('resticbackend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restic.resticbackend')),
            ],
        ),
    ]
