# Generated by Django 4.1.2 on 2022-10-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResticConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResticRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SFTPBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_host', models.URLField()),
                ('ssh_port', models.IntegerField()),
                ('ssh_private_key', models.TextField()),
                ('restic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restic.resticconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
