#!/bin/sh

printf "\033[1m"
printf "\n--- \033[4mrestic-docker-swarm-agent\033[0m\033[1m ---\033[0m\n\n"

printf "* The 'restic' backup utility is installed in this container.\n"
printf "  Run 'restic -h' for help.\n\n"

printf "* You can run restic on the configured backup remote with 'rds-run'.\n"
printf "  Run 'rds-run -h' for help.\n\n"

if [ "$(whoami)" = "root" ]; then
    printf "Note: You're running as root. Unless you need the permissions,\n"
    printf "consider changing to the user 'restic' by running 'su restic'.\n\n"
fi
